version: '3.8'

services:
  api:
    build: .
    ports:
      - "5555:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=TodoAppDb;Username=postgres;Password=ElephantGateKeeper
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
  
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=TodoAppDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ElephantGateKeeper
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d TodoAppDb" ]
      interval: 10s
      timeout: 5s
      retries: 3
        
volumes:
  postgres_data:
            
            